version: '2'
services:
    wplay_misterioso-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/wplay_misterioso/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=wplay_misterioso
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
